# Generated by Django 2.2.5 on 2019-10-19 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True, help_text='Enter election description here')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('total_votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VotedUsers',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer')], max_length=20)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sffrg.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40, unique=True)),
                ('state', models.CharField(default='VA', max_length=2)),
                ('party', models.CharField(max_length=20)),
                ('votes', models.IntegerField(default=0, editable=False)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sffrg.Election')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sffrg.Position')),
            ],
        ),
    ]
