# Generated by Django 2.2.5 on 2019-10-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sffrg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
