# Generated by Django 2.2.5 on 2019-10-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sffrg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='title',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
