# Generated by Django 2.2.5 on 2019-10-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sffrg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votedusers',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
