# Generated by Django 2.2.5 on 2019-11-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sffrg', '0002_auto_20191022_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='candidate_images'),
        ),
    ]
