# Generated by Django 2.2.5 on 2019-10-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sffrg', '0002_auto_20191013_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
