# Generated by Django 2.2.5 on 2019-11-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sffrg', '0004_auto_20191114_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='avatar',
            field=models.ImageField(default='candidate_images/placeholder.jpg', upload_to='candidate_images'),
        ),
    ]
