# Generated by Django 2.2.5 on 2019-10-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sffrg', '0004_auto_20191003_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(max_length=63),
        ),
    ]
