# Generated by Django 2.2.5 on 2019-10-13 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sffrg', '0004_auto_20191013_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer')], null=True, on_delete=django.db.models.deletion.CASCADE, to='sffrg.Position'),
        ),
    ]
