# Generated by Django 2.2.5 on 2019-11-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sffrg', '0005_auto_20191114_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='description',
            field=models.TextField(default='No additional information to display.'),
        ),
    ]
