# Generated by Django 2.2.5 on 2019-11-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sffrg', '0006_candidate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='website',
            field=models.CharField(default='#', max_length=60),
        ),
    ]
