# Generated by Django 2.2.5 on 2019-10-13 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sffrg', '0007_auto_20191013_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sffrg.Position'),
        ),
    ]
