# Generated by Django 2.2.5 on 2019-10-14 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sffrg', '0008_auto_20191013_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sffrg.Election')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sffrg.Position')),
            ],
        ),
    ]
