# Generated by Django 2.2.5 on 2019-10-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sffrg', '0009_votedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='votedusers',
            name='idNum',
            field=models.CharField(default=0, max_length=33),
        ),
    ]
