# Generated by Django 2.2.5 on 2019-10-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sffrg', '0010_votedusers_idnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votedusers',
            name='idNum',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
