# Generated by Django 2.2.5 on 2019-10-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sffrg', '0011_auto_20191014_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votedusers',
            name='idNum',
        ),
        migrations.AlterField(
            model_name='votedusers',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
