# Generated by Django 2.2.5 on 2019-10-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sffrg', '0013_remove_votedusers_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votedusers',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
