# Generated by Django 2.2.5 on 2019-10-03 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='zip_code',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
