# Generated by Django 2.2.5 on 2019-10-19 20:09

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
