# Generated by Django 2.2.5 on 2019-10-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191003_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
