# Generated by Django 2.2.5 on 2019-10-19 20:09

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191019_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
