# Generated by Django 2.2.5 on 2019-10-31 01:08

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_citizen'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ssn',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
