# Generated by Django 2.2.5 on 2019-10-31 01:38

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='street',
            field=encrypted_model_fields.fields.EncryptedTextField(default='700 Park Ave'),
            preserve_default=False,
        ),
    ]
