# Generated by Django 2.2.5 on 2019-10-31 01:44

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='city',
            field=encrypted_model_fields.fields.EncryptedCharField(default='Norfolk'),
            preserve_default=False,
        ),
    ]
