# Generated by Django 2.2.5 on 2019-10-31 01:48

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='qualified',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=True),
        ),
    ]
