# Generated by Django 2.2.5 on 2019-10-31 01:49

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_account_qualified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='qualified',
        ),
        migrations.AddField(
            model_name='account',
            name='disqualified',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=False),
        ),
    ]
