# Generated by Django 2.2.5 on 2019-10-31 01:49

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191030_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='restored',
            field=encrypted_model_fields.fields.EncryptedBooleanField(blank=True, null=True),
        ),
    ]
