# Generated by Django 2.2.5 on 2019-10-31 01:51

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_account_restored'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active_mil',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=False),
        ),
    ]
