# Generated by Django 2.2.5 on 2019-10-31 02:04

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_account_active_mil'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sig',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=True),
        ),
    ]
