# Generated by Django 2.2.5 on 2019-10-31 02:05

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_account_sig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='active_mil',
            field=encrypted_model_fields.fields.EncryptedBooleanField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='sig',
            field=encrypted_model_fields.fields.EncryptedBooleanField(),
        ),
    ]
