# Generated by Django 2.2.5 on 2019-11-02 17:36

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20191030_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='restored',
            field=encrypted_model_fields.fields.EncryptedBooleanField(blank=True, default=False, null=True),
        ),
    ]
