# Generated by Django 2.2.5 on 2019-11-02 20:10

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20191102_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sig',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=False),
        ),
    ]
