# Generated by Django 2.2.5 on 2019-11-05 15:30

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20191105_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='disqualified',
            field=encrypted_model_fields.fields.EncryptedCharField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='restored',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=False, null=True),
        ),
    ]
