# Generated by Django 2.2.5 on 2019-11-05 16:05

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20191105_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='active_mil',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='sig',
            field=encrypted_model_fields.fields.EncryptedCharField(default=False),
        ),
    ]
