# Generated by Django 2.2.5 on 2019-11-05 17:34

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20191105_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='restored',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
