# Generated by Django 2.2.5 on 2019-11-06 00:55

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20191105_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='middle_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='n/a', null=True),
        ),
    ]
