# Generated by Django 2.2.5 on 2019-11-06 01:02

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20191105_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='middle_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
